### ISSUE TITLE
Nori::StringWithAttributes should implement `#as_json`

### ISSUE THREAD

**Issue by HarlemSquirrel** [savonrb/nori#99]
Sidekiq 7 now requires that arguments serialize "safely" to JSON. This means they need to become basic types such as `String`.

Right now, trying to send an object with a `Nori::StringWithAttributes` to a Sidekiq worker queue raises an `ArgumentError` with something like 

> Job arguments to SomeWorker must be native JSON types, but "OK" is a Nori::StringWithAttributes.
> See https://github.com/sidekiq/sidekiq/wiki/Best-Practices
> To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.

**Comment by pcai** [comment]
Coming back to this: if you need lossless transmission of some data:
- transmit it as XML, and then process it with nori on the other side. 

If you are OK with losing some data:
- do the conversion yourself to a basic data type (like String). 

I'm looking at the history of this project and can only conclude that seamless serialization/deserialization of parsed data in memory is not really in scope, since we already have a solution for that: XML.

Thoughts? Am I missing a perspective here?

**Comment by pcai** [comment]
See above

**Comment by rubiii** [comment]
Thank you very much for raising this issue @HarlemSquirrel!
We're moving into the direction if replacing our custom String and StringIO classes with a simpler Hash-based syntax proposed in https://github.com/savonrb/nori/pull/106. There's a new v2.9.0 out that includes a :serializable option to opt-in to that feature as well as a new :standards profile which disables several legacy features. Check out the [changelog](https://github.com/savonrb/nori/blob/main/CHANGELOG.md). Hope this works for you as well.

Also related: https://github.com/savonrb/nori/issues/107
